defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null #space_sim/conf/outputs
  job:
    name: space environment simulation1 # set job name
  run:
    dir: .
      
seed: 1

satellite:
  name: satellite
  mesh: 
    points: [[1.0,0.5,0.5],[-1.0,0.5,0.5],[1.0,0.5,-0.5],[-1.0,0.5,-0.5],[1.0,-0.5,0.5],[-1.0,-0.5,0.5],[1.0,-0.5,-0.5],[-1.0,-0.5,-0.5]]
    lines: [[0,1],[0,2],[1,3],[2,3],[4,5],[4,6],[5,7],[6,7],[0,4],[1,5],[2,6],[3,7]]
  dynamics:
    timestep: 3
    horizon: 5
    pos: [0, 0, 0]
    initial_orbit:
      a: 35786
      ecc: 0.0
      inc: 1.85
      raan: 49.526
      argp: 286.537
      nu: 0
    initial_state_data:
      momentum_wheel_vel: [0,0,0]
    spacecraft_data:
      J_sc: [1.7e4, 2.7e4, 2.7e4]
      alpha: [0.8, 0.8, 0.8]
      mass: 4000

path_planner:
  goal_state: [0,35,0,0,0,0,0,0,0,0,0,0,0,0,0]
  path_planning_algorithm: VFH
  kwargs:
    radius: 20
    min_obstacle_distance: 6
    iterations: 1
    distance_tolerance: 0.5
    layers: 5
    angle_sections: 12
  max_distance: 0.3
  interpolation_method: spline

env:
  control_method: MPC
  point_cloud_size: 400
  path_point_tolerance: 0.1
  point_cloud_radius: 30
  goal_tolerance: 0.1
  kwargs:
    upper_state_bounds: [1e10,  1e10,  1e10, 1e10, 1e10, 1e10, 0.2, 0.2, 6.2832, .25, .25, .25, 1000, 1000, 1000]
    lower_state_bounds: [-1e10,  -1e10,  -1e10, -1e10, -1e10, -1e10, -0.2, -0.2, -6.2832, -.25, -.25, -.25, -1000, -1000, -1000]
    horizon: 20
    valued_actions: 1

#IMPORTANT: when creating a randomly initiated env, make sure that point_cloud_size > n!
random:
  on: False
  n: 10
  vel: 0.003
  x_range: [-20,20]
  y_range: [-5,40]
  z_range: [-20,20]
  stl: stl_files/ball.stl
  stl_scale: 0.001

adversary:
  on: True
  name: adversary
  pos: [0, 8, 0]
  vel: [-0.00416, 0, -0.00416]
  stl: stl_files/ball.stl
  stl_scale: 0.001
  control_lim: [0.1,0.1,0.1,0.1,0.1,0.1,1000,1000,1000]

obstacles:
  #obstacle1:
    #name: debris2
    #pos: [0, 20, -10]
    #vel: [0, 0, 0.001]
    #stl: stl_files/ball.stl
    #stl_scale: 0.001
  #obstacle2:
    #name: debris3
    #pos: [0, 17, 0]
    #vel: [0, 0, 0]
    #stl: stl_files/ball.stl
    #stl_scale: 0.001
  #obstacle3:
    #name: debris4
    #pos: [10, 24, 2]
    #vel: [-0.0012, 0, 0.0005]
    #stl: stl_files/ball.stl
    #stl_scale: 0.001
  #obstacle2:
    #name: debris2
    #pos: [10, 5, 3]
    #vel: [-0.0001, -0.0005, 0]
    #stl: stl_files/ball.stl
    #stl_scale: 0.00333
  #obstacle3:
    #name: debris2
    #pos: [20, 15, -3]
    #vel: [-0.0001, -0.0005, 0]
    #stl: stl_files/ball.stl
    #stl_scale: 0.00333
  #obstacle4:
    #name: debris2
    #pos: [0, 15, 5]
    #vel: [0.001, -0.0015, 0]
    #stl: stl_files/ball.stl
    #stl_scale: 0.00333
  #obstacle5:
    #name: debris2
    #pos: [15, 0, 2]
    #vel: [-0.0001, -0.0005, 0]
    #stl: stl_files/ball.stl
    #stl_scale: 0.00333